version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/app/travis/build/
    overwrite : yes

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 80
      runas: root